#https://styleci.readme.io/docs/multi-lang#section-css-config
css:
  tab-width: 2
  use-tabs: false
  print-width: 120
  double-quotes: false
  finder:
    exclude:
      - node_modules
    name:
      - "*.scss"
